# Generated by Django 5.1.2 on 2024-12-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekyshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
